[project]
name = "cbfs-minimal"
channels = ["conda-forge", "bioconda"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "3.11.*"
pip = "*"

[pypi-dependencies]
scikit-learn = ">=1.5.0"
numba = ">=0.60.0"
joblib = ">=1.4.0"
threadpoolctl = ">=3.5.0"
pyreadr = ">=0.5.1"
scanpy = ">=1.10.0"
igraph = ">=0.11.0"
damply = ">=0.9.0"
leidenalg = ">=0.10.2"
neurocombat-sklearn = ">=0.1.3"
cbfs = { path = ".", editable = true }


